# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Project Builds

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Restore Packages
      run: nuget restore Sonic.sln
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Build
      run: msbuild Sonic.sln /t:SonicTheHedgehog /p:Configuration=Debug
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        # Artifact name
        name: DLLs
        path: .\SonicTheHedgehog\bin\Debug\netstandard2.0\
        if-no-files-found: error
        retention-days: 1
